### ISSUE TITLE
ludusavi.portable not working

### ISSUE THREAD

**Issue by johnnyhunt2000** [mtkennerly/ludusavi#103]
I'm trying to move the config folder to a new folder with the ludusavi exe in it so I created the ludusavi.portable file but it does not seem to work. Any help?
![Screenshot 2022-07-03 005509](https://user-images.githubusercontent.com/54756140/177026914-c33ff61d-8868-414e-8e78-f0da9e179fa4.png)

**Comment by mtkennerly** [comment]
Hi! As you can see in the "type" column, it's listed as a text document, which means the real name is `ludusavi.portable.txt`. With the correct name, that column would say "PORTABLE file".

One option is to rename it in Command Prompt:

```
rename E:\ludusavi\ludusavi.portable.txt ludusavi.portable
```

Or you can enable "show file name extensions" in Windows Explorer so that it lets you remove the `.txt` extension when renaming the file (screenshot from Windows 11 - might be in a different spot on your version of Windows):

![image](https://user-images.githubusercontent.com/4934192/177037360-15f61db5-c9f6-4841-8467-be586bf2f5b1.png)

**Comment by johnnyhunt2000** [comment]
I see now, wasn't aware I had to change the file extension. I figured it out now. Thanks for the help
