### ISSUE TITLE
Manually fetch data for a PCGW entry not yet in local manifest.yaml

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#137]
### What's your idea?

When a game is new and its PCGW entry has only just been created, or, when a PCGW entry has only just had its config/data paths populated/updated, being able to manually fetch that entry's live data would be useful because the ludusavi-manifest github-actions bot only fetches PCGW's recent changes every 24 hours.

In my case, I've created a PCGW page with the appropriate config/data paths for a game and would now like to use Ludusavi to back up its data, problem is, I can't due to the bot's fetch rate.

If we could provide a URL to the PCGW entry and download that data into our local manifest.yaml, we wouldn't need to rely upon the bot's fetch rate for individual games which we want to back up _now_. Granted, this only solves a situation that may not be encountered often by the average user, but if you're like me, I'd rather first make a PCGW edit and then immediately leverage the power of Ludusavi for game's that's missing. A potential ~24 hour wait doesn't motivate to contribute to PCGW, but a quick turnaround would (make PCGW edit > add URL > back up using Ludusavi). These URLs would be a temporary solution before the latest bot-fetched manifest.yaml is downloaded.

Having a local manifest.yaml more current than the one on GitHub could introduce some new issues. For example, when Ludusavi is launched again and the latest GitHub manifest is downloaded (I assume this is performed each launch / once a day), the manually added PCGW data would be lost unless it is written to a separate YAML, or marked in manifest.yaml with some new key-value pair to indicate its temporary. Maybe it being lost is actually fine, because the latest downloaded manifest.yaml should now contain the data that the user manually added via URL.

I don't know if this should be how it works, I'd just like a way to use Ludusavi based upon live data, not data that's potentially 24-hours old.

Thanks.

Ludusavi 0.13.1

**Comment by mtkennerly** [comment]
I just ran a manual update to help you out for now.

The manifest data is mainly sourced from the wiki, but also from Steam's API, and now an override file in the manifest repo to fix things like Overwatch 2 replacing Overwatch. So the wiki link alone wouldn't give you a complete entry. Also, including the functionality directly in Ludusavi means that any manifest import issues/changes would require a new release, which I'd like to avoid. There's also the potential issue of rate limits in PCGW/Steam if an individual decided to spam the refresh (although that's just as true for their normal APIs without going through Ludusavi).

I could increase the update rate for the manifest repo. Since it's just a single instance, there shouldn't be any rate limit issues with PCGW/Steam even if it ran every 15 minutes. However, that means every time you open Ludusavi, it has to download a new copy, which would put more of a burden on GitHub.

I think this combination of things would work:

* In the next Ludusavi version, start storing the timestamp when we checked for manifest updates. On launch, if it's been over 24 hours, then look for an update. Add a button to bypass the 24 hours and check immediately.
* Increase the manifest update rate to every 15 minutes.

That would make updates available much more quickly, but keep the automatic download rate the same.

**Comment by redactedscribe** [comment]
> I just ran a manual update to help you out for now.

Thank you.

> ... the wiki link alone wouldn't give you a complete entry. 

I see.

> That would make updates available much more quickly, but keep the automatic download rate the same.

Sounds like a good compromise based upon everything else you stated. A max of 15 minutes is certainly better than potentially 24 hours if you need an update relatively soon.

Thanks.

**Comment by redactedscribe** [comment]
8c604b3 is a useful addition, but could there be some feedback displayed on the main interface? Nothing fancy needed: If the manifest is being downloaded, "Downloading manifest..." in the top corner or something, just so that we know that a Preview would show us old data if pressed at that moment. In fact, better would be to just notify on-press of Preview that the manifest is downloading and be asked whether to wait or preview anyway.

The manifest doesn't take too much time to download, but it's the preview time which causes the let-down (it can take over a minute to preview, and if one is waiting for the results which are only going to show outdated info, I'd rather cancel, wait until the manifest is downloaded, and run the preview again).

**Comment by mtkennerly** [comment]
Sure, that sounds like a good idea. I went with the first option to keep things simple for now:

> <img width="764" alt="image" src="https://user-images.githubusercontent.com/4934192/195462128-f1157baa-0d5a-47f6-aab0-64034f128e7b.png">

**Comment by mtkennerly** [comment]
I think the changes to the app are complete for this. I've just switched the manifest to update every 6 hours as a trial, and I'll monitor it to see how consistent the timing is and how often it finds changes. If everything goes well, I can increase the rate further after  v0.14.0 is released.

**Comment by redactedscribe** [comment]
Sounds good. Thanks for the implementations, even if they're only intermediate ones at this point. 6 is better than 24, and with any luck, 0.25 will be better still.
