### ISSUE TITLE
Backup structure: use relative paths instead of absolute

### ISSUE THREAD

**Issue by SuperSamus** [mtkennerly/ludusavi#156]
### What's your idea?

Ok, I know I'm asking for a lot here...

Currently, backup paths are absolute. This makes backups pretty unflexible in cases like:
- A user plays the same game on two different computers with a different username.
- The game is moved to another location, and the save data is moved along with it (e.g. Wine prefixes).
- A user wants to sync between different operating systems.

The first two can be somewhat mitigated with the redirect feature, but it's definitely not an option for the latter. Even then, having to manually redirect isn't the most appealing thing for a user. So, I wanted to propose this different system.

The backup structure contains only the necessary files for the save data. For example, if PCGamingWiki says that the save is located to `/path/to/save`, and Ludusavi finds the absolute path of the save to be `/path/to/save/player1/data.sav`, then only `player1/data.sav` will be saved.

(I'm going to imply some inexistent features for `mapping.yaml`, like storing the stores the game is detected from, or the last used path from each OS (with Wine prefixes also counting as Windows paths, relative to the prefix path), but some of that stuff can be for later)

Now, for the restore functionality, it's impossible to have one size fit all. Thus, my idea is to offer options on where to restore data, a global one, and game-by-game. There is also a toggleable checkbox that makes them fallback to using the absolute path (old behavior) instead of failing. These options are (the list is Linux-focused, it can probably be simplified on Windows):
- **Smart** (meant to be the default): use _existing save_. If it fails, tries to understand how a game is installed (I leave this bit vague and to be extended later, but for example Steam games indicate it), then restores in the appropriate way (_native_ if the game is installed natively, _wine prefix_ if it's in a specific Wine prefix). If that also fails, falls back to _native_ (and warns).
- **Existing save**: if the game has a ready-to-be-backed-up save, then that's the path that will be used for the restore. If it's not, tries to get help from the absolute path stored in `mapping.yaml` (for Windows' backups, also looking in the configured Wine prefixes). Fails if no existing save for the game is found, or if multiple are found (I'm not getting into that).
- **Native**: restores to the save path of the native operating system. Fails if the game doesn't exist for this OS, or if the save path depends on the game install path (and it's not found). Warns if the game is installed though a store not compatible with the OS (e.g. a game that supports Linux installed from the Epic Games Store).
- **Wine prefix <prefix>**: Use Windows' _native_ on the specified Wine prefix. Mostly meant for integration for Lutris-like apps.
  - With the fallback checkbox, the absolute path is relative to the prefix.

(There is of course a button to (de)select all games with a warning.)

Finally, there are:
- **Same location**: the old behavior.
- **Custom path**: self-explanatory, for exceptional cases.

So... I don't know, tell me what you think.

**Comment by mtkennerly** [comment]
Hi! Thanks for taking the time to write this up. I'm open to considering larger changes like this, but I don't think this approach would be able to solve the cases you mentioned, at least not in a consistent/foolproof way. There are a lot of edge cases and open questions to consider. The advantage of redirects is that they're opt-in and you know exactly what you're asking for; to avoid them, we potentially have to make a lot of assumptions.

> A user plays the same game on two different computers with a different username.

I think it's pretty simple to use bidirectional redirects for this. On every computer you use, you just need one redirect, like this:

* On your desktop: source = `/home/foo` and target = `/normalized/home`
* On your Steam Deck: source = `/home/deck` and target = `/normalized/home`

We could try to streamline it by adding a `home` folder along with the `drive-X` folders. When we back up a file from the current user's home, we could store it there, and whenever we restore a `home` save, we could put it in the current user's home folder. However, what do we do if...

* ...you have backups for multiple users? Maybe you want a system-wide restore, but now you have to run it as the same user who made the backup originally, or else the saves won't go to the original location.
* ...you have scheduled backups that run under a service account or root? This might require a special case to handle.
* ...you have a custom "home folder"-type root? Does this need to be tied to the current user at all?

> The game is moved to another location, and the save data is moved along with it (e.g. Wine prefixes).

What do we do if you have the same game installed in multiple places? For example, I have three copies of Dead Cells, and these are their save locations for the same file:

* C:/GOG Games/Dead Cells/save/user_0.dat
* C:/Program Files (x86)/Steam/userdata/123.../588650/remote/user_0.dat
* C:/Users/mtken/Games/Heroic/Dead Cells/save/user_0.dat

Normally, I only have a Steam root configured, but I add my GOG and Heroic roots for testing. Let's say I run a backup with my Steam root, then I remove the Steam root and add the GOG root, and then I run a restore. How would Ludusavi know if the game moved or if it's a different installation?

We could probably filter it by root type and say that moves are only possible for the same store. However, then the problem becomes multiple roots of the same type. What if I have two "other" roots with the same game? Maybe you have multiple copies of the same game with different mods installed. Would Ludusavi disambiguate this with some heuristics, with some settings, or just by prompting the user when the situation arises?

> A user wants to sync between different operating systems.

This is inherently tricky because even the same game may not store its saves in logically equivalent places on different OSes. For example, [Celeste](https://www.pcgamingwiki.com/wiki/Celeste#Game_data) stores its saves in the game's own folder on Windows (but *not* if you're using the Microsoft Store version), but uses global folders on Linux and Mac. Ludusavi has no way of knowing that `<path-to-game>\Saves\settings.celeste` and `$XDG_DATA_HOME/Celeste/Saves/settings.celeste` are interchangeable files. Even if we backed them up without absolute paths, Ludusavi would just try to restore your Windows Celeste saves to the game's own folder on Linux, which would be wrong.

Setting up cross-OS redirects is definitely a pain, but unfortunately, Ludusavi just doesn't have enough data to automate this.

**Comment by SuperSamus** [comment]
(Assuming we are on Linux now) So, I made _existing save_ the main method of restore (it's the first thing that _smart_ does, and the second option in the list), and that's for a reason: in the worst case scenario, if it's hard to find out where a save should be restored like in that Celeste case, then _smart_ would give a warning, indicating that the user may not want to restore to `$XDG_DATA_HOME/Celeste/Saves/settings.celeste` (because maybe it's installed on a Wine prefix). If the user has no idea, they could launch the game once (so that a save is created), so then Ludusavi would find a folder where the save exist, and that's where it can be restored.

Of course, if a backed-up game has never been restored on this device, then there should be a warning when trying to backup the same game: overriding an existing save with a new one would be a disaster! (I'm implying that Ludusavi stores on the device which backups have been restored on this device, and on what path)

(With warning I mean making the game background orange and not selecting it by default. I don't know if it already exists.)

(BTW, I'll repeat this)
> The backup structure contains only the necessary files for the save data. For example, if PCGamingWiki says that the save is located to `/path/to/save`, and Ludusavi finds the absolute path of the save to be `/path/to/save/player1/data.sav`, then only `player1/data.sav` will be saved.

(The last used absolute path is still saved in `mainfest.yaml` for fallback)

For the other questions:
> You have backups for multiple users? Maybe you want a system-wide restore, but now you have to run it as the same user who made the backup originally, or else the saves won't go to the original location.
 What if I have two "other" roots with the same game?
 What do we do if you have the same game installed in multiple places? For example, I have three copies of Dead Cells, and these are their save locations for the same file:

I assumed that every user would manage their own backups (each containing a single root for each game) in their own separate backup folder. However, I did say that there should be an option for the old behavior (and a checkbox to fall back to it for the other options). For now, if there are duplicates while restoring, then using the old behavior for them is the only possible option for them until only one is selected. With this, it should be possible for those who were doing this to still do it. A profile system or something for managing these cases is something that can be brainstormed later.

>    ...you have scheduled backups that run under a service account or root? This might require a special case to handle.
    ...you have a custom "home folder"-type root? Does this need to be tied to the current user at all?

If it's for a single user, an _override home_ or something should do it.

> Let's say I run a backup with my Steam root, then I remove the Steam root and add the GOG root, and then I run a restore. How would Ludusavi know if the game moved or if it's a different installation?

Put a warning: only the user can know if they intend to restore to the different path (they also may want to transfer the save store-wide after all).

**Comment by mtkennerly** [comment]
> in the worst case scenario, if it's hard to find out where a save should be restored like in that Celeste case, then *smart* would give a warning

I think this is the common scenario, not the worst case scenario. A large number of cases would trigger this warning:

* Any saves from AppData on Windows or XDG_DATA_HOME on Linux when crossing OSes
* Any saves from PC 1 where the game is not installed on PC 2
* Any games that are installed multiple times
* Any games that were found in one root type and are now found in another root type

> If the user has no idea, they could launch the game once (so that a save is created), so then Ludusavi would find a folder where the save exist, and that's where it can be restored.

I think it's important to be able to restore saves without them already existing and without having to install the game. The last time I switched computers, I bulk restored all my save data with a couple of redirects and without installing any games first. Yes, we could show a warning and ask the user for help, but then they may as well set up redirects.

I don't think Ludusavi should automatically restore saves to a different location than they were backed up just because a game is installed in a new place. It could work in some simple cases, but I think it may be surprising/error-prone, and more complex cases would user assistance anyway.

> Put a warning: only the user can know if they intend to restore to the different path (they also may want to transfer the save store-wide after all).

If we'll have to show a warning and prompt for user intervention in a large number of cases anyway, what's the advantage over redirects?

**Comment by SuperSamus** [comment]
What I'm trying to say is:
When a user sets up a new computer and wants to restore a game for the first time, they need to be careful, which is why many things trigger a warning. After they've looked at everything and restored every game, then there will be no warnings.

When restoring, the user only asks themselves the question: "Where do I want to restore?". They shouldn't have to also wonder: "Where did I backup from?". The latter should only be a tool for the use cases you mentioned. 

> If we'll have to show a warning and prompt for user intervention in a large number of cases anyway, what's the advantage over redirects?

Other than having the "Where did I backup from?" problem, they have the huge issue of being a univalent relation: every path can only be redirected to a single path.
Imagine someone who was using Windows now also using Linux on another computer. The user plays many Windows only games, and they reinstall them on Linux using Lutris. With Lutris, every game ends up in its own Wine prefix.
The user wants to restore these games, but with the current method, how do they redirect that? It's impossible.

With the things I'm proposing, now the user can either (I'm repeating myself here):
- Point every game to the correct Wine prefix. This only needs to be done only once per game.
- Have a workflow of: Launch game > "Whoops, I need to restore" > Restore. This only needs to be done only once per game.
- (In a possible future) Lutris gains Ludusavi integration, and because it knows which prefix the games are installed in, it can say to Ludusavi "restore this game to this Wine prefix" (it was one of the options I listed). No more user intervention per game!

> I don't think Ludusavi should automatically restore saves to a different location than they were backed up just because a game is installed in a new place.

Yes, that should also require user intervention.
(TL;DR user intervention is required when restoring a game for the first time on this device, and when save data is moved. This mess is all mostly because of Wine prefixes, the user has a much easier life if they go all native with everything, which is why I listed it as an option.)

**Comment by mtkennerly** [comment]
By the way, I do think these are important use cases worth trying to improve. I don't necessarily want to solve it by using relative paths (and I've mainly been focusing on the feasibility of that specific detail), but I think the end goal is good!

Just to summarize the use cases so far:

* Restoring on a new computer for the first time: Assuming it's the same OS family and the same username, I don't think this should raise warnings or require intervention (by default, but of course there could always be an option). If the OS or username changes, then I think adding some warnings could make sense.
* Different computers + different usernames: I think redirects are fine for this. I wouldn't mind adding a warning if the username doesn't already exist on the system.
* Same computer + relocated game: I think redirects are fine for this. It shouldn't happen super often, and when it does, it's probably a bulk move like reinstalling Steam.
* Different computers + different OS + game without Wine prefix: I think some kind of cross-OS warning could make sense, as long as it's not intrusive for people who know what they're doing.
* Different computers + different OS + game with native Windows paths to/from Wine prefix: This is definitely a pain point for Windows + Steam Deck users. I think this might be easier to solve for Steam than for other software using Wine/Proton, since we already have thorough coverage of Steam IDs to map the folders. Converting between Heroic and Lutris prefixes, for example, would be more difficult since we don't necessarily have their IDs mapped out.

I'd definitely prefer starting with use cases that we can reliably automate, before something like asking the user to manually map Windows games to Wine prefixes individually. There's still value in something like that, but most people don't want to deal with it 😅

**Comment by SuperSamus** [comment]
I'm still not a fan of redirects. Other than the reasons I already described, for example:

> Same computer + relocated game: I think redirects are fine for this. It shouldn't happen super often, and when it does, it's probably a bulk move like reinstalling Steam.

What if not every game in the folder was moved? What if they were moved to different locations? The univalency of redirects makes them limiting.

I wouldn't mind if redirects weren't a "persistent option", but as a restore setting (that are valid only for that specific restore). For example, in the case of:

> Different computers + different usernames: I think redirects are fine for this.

The user is setting up their new computer: they are going to reinstall the games in the exact way, so they put in the restore settings to use absolute paths but with redirects so that they go to the correct home. After that, they switch to _override save_ and completely forget about redirects. Only disadvantage is with new games.

I don't know, having redirects be persistent bothers me, though that may be just me. Like, I used the "Where did I backup from?" question as a tool, now I can get that question off your head. But no, instead it's something that stays there, and it's... argh. What if I then move something? Or get another computer? I may have to make some calculations so that redirects put everything in the right place, and that's really not something that I should be worried about.

Sorry for the redirect rant. It's not really the focal point of this (the focal point is what I said in the first post). Everything I said before already makes them optional, so it can be a "just don't use them" for me.

> I'd definitely prefer starting with use cases that we can reliably automate, before something like asking the user to manually map Windows games to Wine prefixes individually.

During the writing I was thinking "structure that can do everything first, automatization later". It's why in the _smart_ setting I said: "I leave [how to detect installed games] vague and to be extended later".

Anyway, I don't think I have much more to say.
I hope my feedback was useful for something to you. In the end, it's your program.

**Comment by SuperSamus** [comment]
So, I have a smaller scale idea, that doesn't involve cross-OS save games, but still allows cross-OS sync.
With that I mean:
- A backup made from Windows is a Windows backup;
- A backup made from Linux is a Linux backup;
- A backup made from Linux, but inside a Wine prefix, is a Windows backup.

For example, you play a Windows game on Linux. After backing it up, right now you'd get (for example) this horrendous path:
`drive-0/home/username/Games/prefixname/drive_c/users/username/AppData/Local/game`

With my proposal, you'd just get instead:
`drive-C/users/username/AppData/Local/game`

And Ludusavi saves the fact that on Linux[^1] the prefix is located at `/home/username/Games/prefixname`.
So, when you transfer the backup to Windows and restore it, Ludusavi will simply ignore the prefix.

It'll a bit trickier the other way around, because when trying to restore the Windows backup on Linux for the first time, Ludusavi won't know in what prefix it should be placed in, thus the UI will have to ask the user.

What do you think?

(And there should be buttons to manually change the prefix on Ludusavi, for example because the user moved it.
Also, if the prefix is saved in Ludusavi, but it doesn't exist in the filesystem, maybe a visual warning wouldn't hurt: Ludusavi can't know if the user is simply restoring from a new machine or if they moved the prefix.)

[^1]: Because there's also Mac with Crossover, where the prefix will probably be placed somewhere else.

**Comment by mtkennerly** [comment]
I think that sounds like a good option :) I opened a ticket for it: https://github.com/mtkennerly/ludusavi/issues/194

One wrinkle is that a single backup on Linux might contain files from multiple prefixes, so I think mapping.yaml would still need the raw `drive-0/.../prefixname/drive_c/...` path. The approach in https://github.com/mtkennerly/ludusavi/issues/194 should be able to handle that so we could show the nice translated path in the GUI.

**Comment by SuperSamus** [comment]
Another wrinkle is in case the Windows game saves its data in the installation folder.
If the game is not installed in a Wine prefix, then Ludusavi will detect it as a Linux save.
For games installed in a shared drive (that is, both Windows and Linux see the same save path), this could be a problem.
Maybe there should be a special tag for that. It's a bit of a mess since games are very inconsistent on how to save data across OSes.
