### ISSUE TITLE
cli compression level

### ISSUE THREAD

**Issue by Tokariew** [mtkennerly/ludusavi#182]
### What's your question?

There is option to specify compression method used via cli, but i don't see option how to specify lvl.
And based on the time which it took to the backup via cli and gui, it seems that cli don't read option from config file when specified method

**Comment by mtkennerly** [comment]
The next release will include a `--compression-level` option.

I don't see an issue with how it falls back to the config file. Rather than comparing CLI vs GUI timing, I would recommend comparing CLI vs CLI with different `--compression` values. Comparing the final backup file size should also be more reliable than comparing the timing.
