### ISSUE TITLE
Other Mode does not crawl past first folder

### ISSUE THREAD

**Issue by thelogicmatrix** [mtkennerly/ludusavi#184]
### Ludusavi version

v0.15.2

### Operating system

Windows

### Installation method

Standalone

### Description

So I had set the root as the folder of [Game Series], the subfolders are each named the games of the series and have the exe of the game. So when I set [Game Series] as a root under the Other catergory, it does not detect the game, and the saves which are under path to game. But when I set the [Game Series Entry 1] as the root, only then does it detect the game saves.

**Comment by mtkennerly** [comment]
Could you share a screenshot of the root path and the scan results? I'd like to double check against the expected paths, but I need to know the specific game(s) and folder names.

**Comment by thelogicmatrix** [comment]
Upon closer inspection I just have a lot of DRM free games that have no support, I've tried updating the manifest after editing the wiki but have not seen any new manifest yet

**Comment by mtkennerly** [comment]
> Also just wondering how does it know that a folder has a game? It might be a naming issue

There are a couple of options:

* By default, Ludusavi will look for the game's name as the install folder. For example, since PCGW has an article titled "[Grisaia Phantom Trigger Vol.1](https://www.pcgamingwiki.com/wiki/Grisaia_Phantom_Trigger_Vol.1)", it should recognize your "Grisaia Phantom Trigger Vol.1" folder.
* If a game is on Steam, then Ludusavi will also check the Steam metadata for any additional install folder names.

Ludusavi will also try to do an approximate match to paper over differences like "Vol.1" vs "Vol 1". However, Ludusavi probably won't recognize `6. The Melody of Grisaia` because of the numerical prefix. I'd have to test it to confirm, but I think the approximate match logic is still too strict for that.

Also, you can also use globs in root paths. For example, rather than having one root for Grisaia (path: `D:\Other Games\Ex\Stars\Grisaia`) and one root for another series, you could use `D:\Other Games\Ex\Stars\*` as the root path.

Of course, as you noticed, PCGW itself doesn't have save data for Vol.1, so Ludusavi won't know what to back up for it. If there's a game that PCGW does have data for, but Ludusavi still doesn't recognize it, then I can try to help narrow down the issue. I would just need an example of a game like that.
