### ISSUE TITLE
Not an issue, just some thoughts

### ISSUE THREAD

**Issue by deathbybandaid** [mtkennerly/ludusavi#20]
Firstly, I'd like to clarify that I have not tried ludusavi yet, but it's been in my bookmarks for a while.
From the README.md, It looks like it does something I've wanted for a while, and I will definately be checking this out.

The below can be taken as seriously as you want, and you may decide it to be "out of scope", but I figured it was better to communicate the ideas than to not.

The timing was funny, as I recently had created a reddit post to r/selfhosted:

https://www.reddit.com/r/selfhosted/comments/gnjv7r/an_idea_for_the_right_dev/

Basically, it seems like it would be a little spin on what you are already doing here since you are already supporting cross-platform.

What I'm suggesting; A server-client setup, a server application that stores the backups. and a client agent that communicates with the server. This would also allow multiple devices to not only backup, but also possibly sync.

The extra work would involve a web interface (for being headless), user management control, api key stuff for authentication.

Another idea that occurred to me as a I was typing this, is that you could even share game saves to other people, if reverse proxied.

**Comment by mtkennerly** [comment]
That's a cool idea, but yeah, I think it's out of scope for Ludusavi itself. That said, someone could definitely incorporate Ludusavi into such a project:

* If the server needs to know about the game save locations, it could use the [Ludusavi Manifest](https://github.com/mtkennerly/ludusavi-manifest).
* The agent could use Ludusavi's command line interface to trigger backups/restores.

I could potentially see the client functionality being integrated directly (similar to #13), bit it would partly depend on whether the agent needs some very OS-specific setup, like installing services, since Ludusavi is meant to be fully portable.

**Comment by sharkusmanch** [comment]
All the tools exist, I think it would just take a thin wrapper program/script to make them work together. Couple that with a Playnite extension, and you could easily backup game saves when a "Game stopped" event occurs.

I put together a quick Ruby POC (not super portable, since it's ruby unfortunately) using [ludusavi-manifest](https://github.com/mtkennerly/ludusavi-manifest) that does the following:

- Super simple extension script to execute the backup command for the game when a "Game Stopped" event occurs.
- Simple ruby script to take a single game name, determine the save data dirs/files for said game, and execute a restic backup on those paths.
- [Restic](https://restic.net/) was the tool I selected to do the actual data backup. Value add here is data de-duplication. Instead of having the identical save data stored 10 times, it's only stored once with subsequent diffs stored as well.
- In my case, I was backing up a [rclone](https://github.com/rclone/rclone) backend repository, which is just a NAS on my local network.

That gives all the benefits of the solution described by @deathbybandaid, while not having to host any services. The user could then configure any arbitrary storage backend for restic/rclone. Also worth noting that rclone and restic are fully cross platform.

Only issues I ran into when doing this were mismatches between how Playnite had named games vs what the ludusavi manifest expected. That could also be solved by creating a Playnite PCGaming wiki metadata provider extension to handle renaming though.

**Comment by mtkennerly** [comment]
I'm gonna mark this as closed for now since there aren't any action items, but please feel free to continue the discussion if you have more thoughts.
