### ISSUE TITLE
Split preview button into rescan / preview

### ISSUE THREAD

**Issue by Xarnowit** [mtkennerly/ludusavi#201]
### What's your idea?

Currently I feel preview button functionality is bit unintuitive because from user perspective it really has two functions: full search for the save data on the disk, and scan for updates to backed up save data. I think it would be better to split this into separate buttons. 
- Rescan - update list of games/save data, useful after installing/uninstalling game etc.
- Preview - scan selected games for changes to save data

Additionally after splitting this functionality it would make sense to auto preview on opening the gui (with the option to turn this off in settings)

**Comment by mtkennerly** [comment]
Internally, these are really the same thing (either a full scan of all possible games or a partial scan of specific games). I think of it as one function: "show me the saves on this system". That said, I could see two main use cases for a new option:

* If you don't care about any new games, then it's faster to do a partial scan. On my system, a full scan is only 10 seconds, so it's not a big deal to stick to full scans.
* If you have filters applied, there's no way right now to *just* preview the games found by the filter. This could definitely be improved.

Since games have to be in the list for you to filter them in the first place, I think it could make sense to say that "preview" and "back up" only apply to visible games when you have a filter active. Alternatively, we could add a "..." menu with a "Preview visible games only" option, independently from any filter.

**Comment by mtkennerly** [comment]
I've implemented this via filtering. This also lets you scan specific subsets of games:

> https://github.com/user-attachments/assets/b15a4578-b87d-4416-9104-592e41c1f430
