### ISSUE TITLE
Restoring from ZIPs is horribly slow

### ISSUE THREAD

**Issue by RuiNtD** [mtkennerly/ludusavi#203]
### Ludusavi version

v0.17.1

### Operating system

Windows

### Installation method

Scoop

### Description

Hello. I'm trying to restore my Prism Launcher save with Ludusavi. The backup is a 7.62 GB large ZIP file and the restore has been running for almost 12 hours now. Process Monitor shows that it is, in fact, actually doing work, but that it's also **constantly** reading the ZIP file. It also seems to only be writing files every 10 seconds at this point. It might a good idea to have Ludusavi instead extract ZIPs file entirely to temp and work from that.

**Comment by mtkennerly** [comment]
Thanks for reporting this. Would you be willing to try a test build? It's a minimal change on top of v0.17.1, without any of the other recent changes in the master branch:

[ludusavi-v0.17.1-post.1+90bb37e-win64.zip](https://github.com/mtkennerly/ludusavi/files/11505605/ludusavi-v0.17.1-post.1%2B90bb37e-win64.zip)

Test results on my system:

* Test: 1 game, 1,536 files, 1.08 GB raw, 0.754 GB zipped (deflate level 6)
  * Restore (before): 1 minute 11 seconds
  * Restore (after): 5 seconds
* Test: 1 game, 12,800 files, 9.07 GB raw, 5.99 GB zipped (deflate level 6)
  * Restore (before): still running, but looks like it'll be 1 hour 30 minutes
  * Restore (after): 1 minute 3 seconds

> It might a good idea to have Ludusavi instead extract ZIPs file entirely to temp and work from that.

The current design allows Ludusavi to only extract the files that have actually changed (let's say if only 20 MB of the 7.62 GB need to be restored). However, it was naively reopening the zip for each file that it wanted. I didn't realize how much of a bottleneck that was because I had been testing with smaller archives (under 300 MB) on an SSD.

There's still room to improve this further. Ludusavi parallelizes work at the game level, but not at the file level. When one game is disproportionately larger like this, if all the other games finish first, then the huge game is still stuck with a single worker thread. Ideally, it should start sharing work with the other available threads. However, that would also be a more invasive change, so I'm hoping the smaller change I just made is enough for now.

**Comment by RuiNtD** [comment]
I’ll try out that build in a few hours. What I was actually suggesting tho is to extract the ZIP file to `TEMP` and do the regular restore process from within `TEMP`, as if the user backed up to that directory without ZIP, then delete the extracted folder. Granted, that would probably only increase performance for larger saves, like maybe over 100 MB?

**Comment by mtkennerly** [comment]
I'm not quite sure how that would help the performance. You'd have one write from the zip to `%TEMP%` and then another write from `%TEMP%` to the final target, as opposed to a single write from the zip to the target. It could be more robust by being an atomic operation (copying a temp file instead of writing directly), but I wouldn't expect it to be faster.

**Comment by RuiNtD** [comment]
games | files | raw size | zipped size | restore (before) | restore (after)
-- | -- | -- | -- | -- | --
1 | 40,864 | 8.70 GB | 7.62 GB | 12+ hours | 00:03:58

Probably still room for improvement, since 7-Zip can extract the ZIP in 00:01:35, but it's not that big of a deal.
