### ISSUE TITLE
What effect does the order of the Root paths have?

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#231]
### What's your question?

As per the title. Does performance change if, for example, paths from the same drive are grouped together? Are paths higher in the list detected sooner? Do any specific paths make sense to come before others? Maybe the answers to these questions are relevant to #roots in README.md?

Thanks.

**Comment by mtkennerly** [comment]
Good question! The short version is that root order shouldn't make any difference, except potentially for secondary manifests.

> Does performance change if, for example, paths from the same drive are grouped together?

I don't believe so, unless there's some magic at the OS level.

> Are paths higher in the list detected sooner?

Yes, they're inspected top to bottom. That's just an implementation detail, though, and it's possible that they could be inspected in parallel or another order in the future.

> Do any specific paths make sense to come before others?

The order shouldn't matter. The information from each root is used independently from the others. The one exception is when it comes to secondary manifests, since Ludusavi merges them together in the order that it finds them. That won't matter if they're just adding new games, but it could make a difference if they're overriding standard games.
