### ISSUE TITLE
Add more tooltips to various parts of the UI

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#232]
### What's your idea?

Some button's icons aren't as self-explanatory as others and so tooltips could be of use. For example the _Add additional root paths_ button on the _Other_ tab is a refresh icon which doesn't really convey what will happen on-press. Same goes for the button between Rclone and Arguments.

Some buttons already have tooltips, specifically those that are hovered over when holding Ctrl / Shift to perform a quick back up etc. These are shown immediately when hovering which I think makes sense, but to do so for all tooltips would probably be a bit unsightly, at least, if many tooltips were introduced. A short delay as is quite typical for tooltips and would help in that case.

For starters, I'd say that the less than obvious buttons should be addressed. I can't see tooltip candidates other than the two which I mentioned.

Thanks.

**Comment by mtkennerly** [comment]
I can add tooltips, but if the icons aren't intuitive, maybe some different icons could help. I'm using [Material Icons](https://fonts.google.com/icons?icon.set=Material+Icons).

> For example the Add additional root paths button on the Other tab is a refresh icon which doesn't really convey what will happen on-press.

Do you think a [search icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asearch%3A) would be clearer?

> Same goes for the button between Rclone and Arguments.

That's the ["file open" icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Afile_open%3A), as opposed to the ["folder open" icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Afolder_open%3A) used for other path selectors. Do you think it would be clearer to use the same folder icon for any path selector, regardless if it's selecting a folder or a file? I could see an argument for that, since the popup should make it clear enough on its own.

**Comment by redactedscribe** [comment]
If a button isn't obvious and its action doesn't make any immediate changes (like clearing a list and saving its state), then you can quickly learn what a button does, e.g. you click it and it only opens the file selector dialog, fine, X out of it. But of course, being self-evident to begin with is the better choice.

The _Add additional root paths_ button is an immediate change IIRC. It's not a big one, root paths can be removed after Ludusavi instantly appends them.

Rather than choosing between text or icon, what about a combination? "🔍 Missing Roots", but search kind of implies the presence of an intermediary step I think. The button's action is more akin to adding since that is the end result, so: "(+) Missing Roots"? But using the same icon as the other "(+)" icons which aren't titled might be odd. Without being overly explicit ("🔍 Find and add missing paths"), just "🔍" with a clarifying tooltip?

> Do you think it would be clearer to use the same folder icon for any path selector, regardless if it's selecting a folder or a file? I could see an argument for that, since the popup should make it clear enough on its own.

That's a good option that doesn't overthink things. IIRC, Windows and Linux support dialog windows of two kinds, one which can pick folders, and one that can pick files (macOS has a unified dialog window that can pick either type of item), so the file icon is indeed fit for the button's purpose, but it's not as universally understood as the folder icon. Strangely enough, the "🔍" icon could be a good fit here since we are picking (searching) for a file. Other options are the "Plagiarism", "Find In Page", and "Insert Drive File" icons (although "Find In Page" is already commonly used for its exact purpose). The last icon would be the most similar to the folder icon and so could be the best choice. I couldn't fine any blank basic file icon other than "Insert Drive File".

**Comment by mtkennerly** [comment]
> The *Add additional root paths* button is an immediate change IIRC. It's not a big one, root paths can be removed after Ludusavi instantly appends them.

There's a confirmation step:

<img width="602" alt="image" src="https://github.com/mtkennerly/ludusavi/assets/4934192/43ea880e-b136-4ec3-8345-d0899edcc45f">

Thanks for the detailed explanation of your experience :) It's very helpful to understand how the icons could come across. Since it has an intermediate step, it sounds like the search icon would be a good fit.

**Comment by mtkennerly** [comment]
Cloud section:

> <img width="574" alt="image" src="https://github.com/mtkennerly/ludusavi/assets/4934192/2bbc1907-3ace-4843-a4da-f8f0cc3ac692">

Root section:

> <img width="578" alt="image" src="https://github.com/mtkennerly/ludusavi/assets/4934192/08b2ae6d-e2e2-4af1-b0b0-109e46d8e9a0">
