### ISSUE TITLE
Keep a backup log

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#25]
This is a follow-up to #16. The idea would be to have a YAML file in the backup folder like this:

```yaml
MTAwMCBBbXBz:
  name: 1000 Amps
  files:
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTE=: D:/Steam/steamapps/common/1000 Amps/save1
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTI=: D:/Steam/steamapps/common/1000 Amps/save2
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTM=: D:/Steam/steamapps/common/1000 Amps/save3
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2V0dGluZ3M=: D:/Steam/steamapps/common/1000 Amps/settings
```

The goal is so that people can quickly check the contents without opening up Ludusavi and to help alleviate the unfamiliarity of Base64 for most users. It would also allow for text searching, since Ludusavi doesn't have that right now.

**Comment by darklinkpower** [comment]
Related to this, I was thinking. Considering the base folder is just the base64 name of the game name, why not remove characters that are not supported in file explorers once this is implemented? If the full game name without character restrictions and the base64 name would already be in this YAML file, it could be used to detect the game name instead of the base folder. This would give the benefit of being more manegeable on the user side and I don't see any cons to this approach. I think some issues that people could have could be solved by managing them in this file if propertly structured, although some things would need to change in how ludusavi currently works.

And sorry if I'm making way too much questions. I really like the project and want to see it improve :)

**Comment by mtkennerly** [comment]
No worries at all! The more the better \:D

I just opened #29 for reorganizing the saves, so I'll respond there to keep the topic centralized.

**Comment by mtkennerly** [comment]
Based on the discussion in #29, this ticket will be obsolete. I'm moving away from Base64 altogether. There will be a slightly similar mapping file, but it will be much simpler.
