### ISSUE TITLE
Gamesave not beeing found/backuped

### ISSUE THREAD

**Issue by Nekotje** [mtkennerly/ludusavi#255]
### Ludusavi version

v0.20.0

### Operating system

Linux

### Installation method

Flatpak

### Description

use this to make copies of my games and im very happy with it. It works pretty good.

Only 1 thing i noticed with 2 games might be more.
![image](https://github.com/mtkennerly/ludusavi/assets/6666518/c94c1442-ccc9-47a0-81e8-ded78ab1704f)

These are my roots where my games are installed.

with the first root entry
/home/User/.steam/debian-installation/
i have a game installed ship graveyard simulator and ship graveyard simulator 2
When i click preview that it does a scan these dont show up in the list.

But when i look at where the save game is
/home/User/.steam/debian-installation/steamapps/compatdata/2201940/pfx/drive_c/users/steamuser/AppData/Local/ShipGraveyard2/Saved/SaveGames/FullSave_AutoSave_001.sav

Its in that Root directory but it does not find it.

Edit:
Somehow affter the paths there is a / which should not be there because it wont find games in those directories if that is there. when its gone its still the same problem with that it doesnt find the game.

**Comment by mtkennerly** [comment]
Hi! This is because PCGamingWiki [doesn't have the save location listed](https://www.pcgamingwiki.com/wiki/Ship_Graveyard_Simulator#Game_data) for the first game, and there's no article for the second game. Ludusavi ultimately gets most of its information from PCGamingWiki.

It would be great if you could add the information to the wiki, and then Ludusavi will automatically incorporate it :) For example, if you add an article for the second game, the save file you mentioned would be represented like this on the wiki (based on its Windows path and using a wildcard for all ".sav" files):

```
{{Game data/saves|Windows|{{p|localappdata}}\ShipGraveyard2\Saved\SaveGames\*.sav}}
```

**Comment by Nekotje** [comment]
I have added it to the first game.  How often is de manifest updated? can you manual force update? 
if i use the refresh button next to manifest  it updates the checked time but not the updated time. So it does not see the game yet.

**Comment by mtkennerly** [comment]
> How often is de manifest updated?

On GitHub, there's a script that runs every 6 hours to check PCGamingWiki and then update the manifest stored on GitHub. After that, Ludusavi has to download the manifest from GitHub onto your system, which either happens when you launch the app (if it's been at least 24 hours since the last check) or when you use that refresh button (which bypasses the 24 hour wait).

Your edit on PCGamingWiki has been added to the manifest (https://github.com/mtkennerly/ludusavi-manifest/commit/f466d8196472d6e0b96c758a31329195112033c2), so you'll get it if you use the refresh button now.

> Here it where the saves stands. 2 locations the first one was already on the gaming wiki.

Since you have `/home/User/.steam/debian-installation` configured as a Steam root, Ludusavi should now find the saves in there.

I don't see `/home/User/.steam/steam` in your configured roots, so it won't find that unless you add it as a Steam root as well. Unless one of your other roots is a symlink to that folder?

**Comment by Nekotje** [comment]
> I don't see `/home/User/.steam/steam` in your configured roots, so it won't find that unless you add it as a Steam root as well. Unless one of your other roots is a symlink to that folder?

Ah well i click that searcher icon and it said no additional roots found. so i kind of forgot about that one.
