### ISSUE TITLE
Option to not backup steam Screenshots when backing up a save

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#26]
I just checked your [Playnite extension for ludosavi](https://github.com/mtkennerly/ludusavi-playnite) and it worked great but I think it would be great to have an option to not import screenshots and in the better of cases, perhaps make this option configurable per game.

And I have another question: When backing up again, does it copy the same files again and overwrite them or does ludosavi detecti if it already exist and that it's the same file without changes to only copy files that have changed?

Also curious as to why use Base64 for naming since it makes things more difficult for manual manipulation on the user side and for other purpose and I don't see what's the benefit with this approach.

P.D: Someone made a thread for the extension here and that's how I knew about the extension, although it would be better if you made an official thread there https://playnite.link/forum/thread-342.html

And linking this relevant issue in Playnite: https://github.com/JosefNemec/Playnite/issues/124

**Comment by mtkennerly** [comment]
Hey there! Thanks for checking this out and for all the feedback.

* Agreed, some filtering options would be good. Some other possible filters, based on the data that Ludusavi has, would be "saves", "config", and "uncategorized" (for entries that we don't know if they're saves or config).

* Ludusavi copies all files for a game, even if they haven't changed since the last backup. Specifically, it deletes the game's previous backup set first, so that any "obsolete" files don't get included - like if you had 10 quick saves and deliberately deleted 5 of them, we don't want the deleted 5 to stay in the backup folder forever and then get restored. I'm definitely open to adding that as an optimization, but I didn't necessarily think it would make a huge difference. On my system, with 227 games and 1,589.91 MiB of data, a preview (scan without copy) takes 15 seconds, and a backup (scan with copy) takes 22 seconds. Are there some other use cases or advantages beyond the time difference?

* There are a few main reasons for using Base64:

  * We need to preserve the full, original location of each file, which, on Windows, means preserving the drive letter or potentially even a UNC path prefix (`\\shared_drive\...`), which can't necessarily be written verbatim in a folder name.
  * It avoids any potential snags from trying to make a folder named after a game when that game has special characters, like .hack//G.U or *** ([yes, that's a real game](https://www.pcgamingwiki.com/wiki/***)).

  I couldn't come up with a straightforward and nicely cross-platform way to encode that information in a more human-readable way. Something like this is tempting:

  ```
  the-backup-folder/
    Celeste/
      C/
        Users/
          ...
  ```

  ...but you'd have to figure out an encoding system for the game name or UNC prefix if it contains special characters (e.g., `.hack{slash}{slash}G.U.`), and you'd need some sort of stand-in for the drive letter on Linux and Mac. There's a trade-off between those alternatives being more human-friendly while at the same time being more "irregular" - it's easy for someone to write a script that looks through some Base64-encoded backups in a flat folder, but it's more complicated for them to reverse some special encodings like `{slash}` and recurse through a nested folder.

I can certainly make a thread on the forum if that's preferred. Is it okay to do that even though FullPrimal already made an announcement?

**Comment by darklinkpower** [comment]
Thanks for the explanation, I agree with your points and #25 would help with this problem.

More than the time difference, I was just curious just to prevent unecessary writes but it's not an issue with time since it's a pretty fast operation anyway.

And yeah, he just made the thread so other people can see it and in my opinion it would be better that the original author made the official thread where he can reply, update the OP with relevant information when necessary and basically have more control.

**Comment by sharkusmanch** [comment]
> P.D: Someone made a thread for the extension here and that's how I knew about the extension, although it would be better if you made an official thread there https://playnite.link/forum/thread-342.html

That was me. @mtkennerly  let me know if you want to make an official one and I can delete it or redirect to yours.

**Comment by mtkennerly** [comment]
@sharkusmanch Yeah, I'll go ahead and make an official thread. Thank you for announcing it, though :D It's really awesome to see people using this. It's up to you as far as delete vs redirect, but I can post a comment in yours when the new thread's up.

**Comment by darklinkpower** [comment]
Now I remember why I initially thought of this scenario:

> And I have another question: When backing up again, does it copy the same files again and overwrite them or does ludosavi detecti if it already exist and that it's the same file without changes to only copy files that have changed?

Since I have a slow connection, having to upload files that have been uploaded before again will eat my connection, which won't load anything when it's in full use and can be problematic for game saves that are more than kbs in size. Not a big deal but I thought I would just mention it.

**Comment by mtkennerly** [comment]
You mean like if you're backing up to a folder that's synchronized with a cloud service? Yeah, if that's triggering a re-upload even though the data is the same, that's not so great. I'll look into that then.

**Comment by mtkennerly** [comment]
> ![image](https://user-images.githubusercontent.com/4934192/89109628-eda80c00-d410-11ea-8394-67387276fc16.png)

Closing since there are separate tickets for the other ideas discussed here.
