### ISSUE TITLE
New games not detected when running backup via command line

### ISSUE THREAD

**Issue by utkarshdalal** [mtkennerly/ludusavi#266]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

Hello,

I have a script that runs `ludusavi backup --force` on boot, and then every 3 minutes. However, if I install a new game, it does not seem to be detected and backed up. Am I doing something wrong? Is there a way for me to force a full scan?

**Comment by mtkennerly** [comment]
Hi! That's the right command for a full scan, so something else must be going wrong here.

* Have you seen this with multiple games? Could you give some examples of specific games and which stores they're from (e.g., Steam) so I can double check the expected save locations?
* How is the script launched? If it's a Windows service, then what user does it run as? If it's running as the generic service account, then it won't find saves in your user-specific folders like `%USERPROFILE%`.

**Comment by utkarshdalal** [comment]
This happened with The Last of Us and Call of Duty Modern Warfare 2, both on Steam.

I believe the script is running as administrator (it runs on boot in the administrator account. but I'll check. Games are found fine when running via the UI.

If there's a logfile somewhere I'm happy to share as well.

**Comment by mtkennerly** [comment]
Both of those games put saves in `%USERPROFILE%`, so that makes sense. There are a few issues with doing the backups from a different user account:

* Ludusavi stores its own configuration in `%USERPROFILE%`, so the script may have put a backup in `C:\Users\Administrator\ludusavi-backup`. You could specify `ludusavi --config C:\Users\utkarshdalal\AppData\ludusavi backup --force` to make it use your regular config.
* Ludusavi will try to resolve `%USERPROFILE%` as `C:\Users\Administrator` when looking for saves, and it will find the admin versions of special folders like Documents and AppData. You can add a "home folder" root pointing to `C:\Users\utkarshdalal` so that Ludusavi will also check there as well, but one limitation is that it will only check the standard special folder locations (like `C:\Users\utkarshdalal\Documents`) and won't adjust if they've been moved or localized.

If you can make the script run as your normal user account, you'll get better results 😅

**Comment by utkarshdalal** [comment]
Hey, so this was an error on my side. Seems to be working, even when the saves are in `/Users/Administrator/AppData...`. I think there just needed to be a new save for it to be detected maybe. Thanks for the speedy response :)

Is there a way to force a full scan for backups every time? I believe just running `ludusavi backup --force` will only run a full scan the first time right?

**Comment by mtkennerly** [comment]
Gotcha, yeah, Ludusavi won't find anything if there's no save data yet. Glad you got it working :)

`ludusavi backup --force` does a full scan every time, so no worries there.

**Comment by utkarshdalal** [comment]
Thank you for the prompt replies 🙂
