### ISSUE TITLE
Git repo as save storage

### ISSUE THREAD

**Issue by Renive** [mtkennerly/ludusavi#293]
### What's your idea?

Hi, is it possible/easy to add to have git repo with saves? And instead of differentials, just commit changed files? A lot of saves are either text or binaries, but binary are always small files. It would be so cool to have git as history instead of differential backups. I think it will be also better for storage and management.

**Comment by mtkennerly** [comment]
Hi! Thanks for your suggestion. I think this is an interesting idea, although my gut feeling is that there might not be enough interest to justify the maintenance and technical challenges, Some initial thoughts:

* Would you expect a shared repo for all games or an individual repo per game? I think individual repos would be cleaner (one commit = one backup), but it would result in a lot of extra Git metadata files, which might not be desirable when using remote/cloud backups.
* How would this interact with the retention limits? The full/differential paradigm might not really be a good fit, but we would need some way to prevent infinite growth of file size. Would that involve rewriting history to squash commits? Would we use separate branches and delete branches at certain points?
* How would this interact with the Rclone/cloud functionality? If you have divergent local and remote backups, do you merge/rebase via Git or just replace the whole repo state via Rclone?
* Right now, it's possible to have a mix of backup types for each game, since simple and zip backups can coexist. I feel like that wouldn't really work with Git backups. What happens if you have some non-Git backups for a game, turn on the Git feature, and then make a new backup? What about the other direction?
* In the future, I'd like to add the option to import/export backups to make it easier to share them. If importing a backup always adds it as the latest one, then that would just mean adding a new commit, and that's easy. However, if someone wanted to import a backup in an older position and lock it (i.e., they want the backup available indefinitely, but they don't want it to represent the current state of their game), then how would we do that?
