### ISSUE TITLE
Lutris gamesaves not detected

### ISSUE THREAD

**Issue by ghost** [mtkennerly/ludusavi#306]
### Ludusavi version

v0.22.0

### Operating system

Linux

### Installation method

Other

### Description

Hi, as said I have several gaems installed through lutris and while it detects the Lutris folder the games are not detected when scanning.

**Comment by mainrs** [comment]
Can you provide the https://lutris.net/ links of the games that do not get detected? This project fetches the save file location from https://www.pcgamingwiki.com. If your games are not picked up, then there is probably no save file location entry on said wiki.

I had the same issue for some games of mine that I got from itch.io. I went to https://www.pcgamingwiki.com and added the save file location. It took less then 24h for ludusavi to pick the locations up and allow me to back them up properly.

**Comment by ZoidbergForPresident** [comment]
> Can you provide the https://lutris.net/ links of the games that do not get detected? This project fetches the save file location from https://www.pcgamingwiki.com. If your games are not picked up, then there is probably no save file location entry on said wiki.
> 
> I had the same issue for some games of mine that I got from itch.io. I went to https://www.pcgamingwiki.com and added the save file location. It took less then 24h for ludusavi to pick the locations up and allow me to back them up properly.

It's streange because at least one game should be detected, Arcade Paradise (GoG), but isn't... maybne I'm badly using the program? I'm kind of a Linux noob. ^^'

**Comment by mainrs** [comment]
That game probably does not work with the GOG installation. PCGamingWiki only has save file location entries for the Steam installation:

https://www.pcgamingwiki.com/wiki/Arcade_Paradise

**Comment by kekonn** [comment]
Just my 2 cents, but I've had this problem when adding games to lutris without using the installer. In that case, the lutris metadata does not contain a name for the game (strange, I know) and thus ludusavi skips importing it. I had to manually edit the lutris yaml file for that games'  metadata to make it work.

**Comment by mtkennerly** [comment]
In this specific case, it does look like the issue is that PCGamingWiki doesn't have enough info on the save locations.

The Ludusavi manifest recently (mid-March) started including Steam Cloud paths for games that don't have any paths on the wiki. In this case, that includes one path: `<home>/AppData/LocalLow/Nosebleed Interactive/Arcade Paradise/<storeUserId>/*.dat`

I'm not sure if that path is correct for GOG, though. If it is, then the game should show up now. If you still don't see it, then it may be related to https://github.com/mtkennerly/ludusavi/issues/209 .
