### ISSUE TITLE
Ben 10: Power Trip not detected on Windows

### ISSUE THREAD

**Issue by gvrocksnow** [mtkennerly/ludusavi#328]
### Ludusavi version

v0.22.0

### Operating system

Windows

### Installation method

Standalone

### Description

The game saves for this game are detected on the Steam Deck after I added the save and config paths to PCGW but on Windows it does not detect them.

**Comment by mtkennerly** [comment]
Hi! The paths on PCGW do look normal. Could you show me a screenshot of Regedit on your Windows system, to double check the exact content of `HKEY_CURRENT_USER\Software\PHL Collective\Ben 10`?

**Comment by gvrocksnow** [comment]
Sure, here you go.
![Capture2](https://github.com/mtkennerly/ludusavi/assets/22365275/19051a81-0ff6-4562-8818-9ef751c67df0)

**Comment by mtkennerly** [comment]
On the wiki, the path ends with `Ben 10` (with a space), but it looks like there's no space in Regedit. Removing the space on the wiki should fix it.

The reason it seems to work on the Steam Deck is because, for Wine prefixes, Ludusavi backs up the whole `*.reg` files if the game saves anything in the registry. On Windows, Ludusavi picks out just the relevant subset of the registry.

**Comment by gvrocksnow** [comment]
Oh. I will update the path. Thank you for the quick support!

**Comment by mtkennerly** [comment]
No problem! The manfiest has been updated, so it should work now :)
