### ISSUE TITLE
Allow the use of a custom "copy" command

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi#34]
## Suggestion:

As a means for more flexible backups, allow the use of an arbitrary backup command. Where the user would supply the entirety of the command and ludusavi fills in the save paths and game name.

Not sure how restores would be handled in this case though.

### standard `cp`:
````
cp #{SAVE_PATHS} /my/backups/location/#{GAME_NAME}
````

### rclone copy
````
rclone copy #{SAVE_PATHS} googledrive:/gamesaves/#{GAME_NAME}
````

### [restic backup](https://github.com/restic/restic)
````
restic backup #{SAVE_PATHS}
````

**Comment by mtkennerly** [comment]
I'm not sure if this is feasible to integrate directly (where you provide a template command and Ludusavi fills in the gaps). There's a lot of associated complexity for full integration:

* Some commands would require individual pairs of source path and target path (`cp`), but maybe not all (your `restic` example doesn't have a target), and some commands might work better with files for one game at a time or with all games' files at once
* You would need a configurable command for creating parent directories (`mkdir -p`)
* You would need a configurable command for deleting the existing backups (when "merge" is unchecked)
* You would need to configure how to tell if it failed (overall failure or individual file failure)
* You might need to configure a command for setting file attributes (#33) or at least a way to skip doing if it doesn't apply
* Is there a special command needed to find the files and mapping.yaml in order to restore?

If you're gonna have to configure all that anyway, I think it would be simpler to use the CLI with `--api` and iterate through the files. That way, you can set it up exactly how you need, without worrying if there's a config for the exact tweaks you need to make. Here's a Python example:

```
import json
import subprocess

result = subprocess.run(
    ["ludusavi", "backup", "--preview", "--api", "1000 Amps"],
    stdout=subprocess.PIPE,
)
data = json.loads(result.stdout)

for game_name, game_info in data["games"].items():
    for file_path, file_info in game_info["files"].items():
        print(file_path)
```

Output:

```
D:/Steam/steamapps/common/1000 Amps/save1
D:/Steam/steamapps/common/1000 Amps/save2
D:/Steam/steamapps/common/1000 Amps/save3
D:/Steam/steamapps/common/1000 Amps/settings
```

You could replace the `print` with the custom command you'd want to run.

The current `--api` data is mostly focused on reporting, but I could definitely add more info that you would need for this use case. How does that sound? Do you know what sort of data you might need added?

**Comment by sharkusmanch** [comment]
Wasn't aware of the `--api` flag. Just tested it and it seems to output everything I would need to handle this on my own, as you suggested.

Thanks!
