### ISSUE TITLE
Custom only mode/only backup previously scanned option

### ISSUE THREAD

**Issue by BuyMyMojo** [mtkennerly/ludusavi#348]
### What's your idea?

I have a portable version of Ludsavi bundled with my files for [FoundryVTT](https://foundryvtt.com/) so I can backup it's data folders but in ordder to have it work nicely for that I needed to add every other drives in my system to the exclusion paths and add every registery result one at a time as using `*` in the registery exclusions does not work.

![image](https://github.com/mtkennerly/ludusavi/assets/46948241/fc751502-9a6f-4b16-839b-8369cc6f20e9)

![image](https://github.com/mtkennerly/ludusavi/assets/46948241/2daf57f9-a1fa-4124-a9af-b9c6b327c852)

I've love both an option to only scan and backup previously scanned locations as well as an option to only scan specifically custom paths and ignore ALL other paths on the system

**Comment by mtkennerly** [comment]
Hi! There's some overlap here with #201 and #260 for re-scanning previously found games.

For only scanning very specific games, here's a solution that may help you. Create two files:

* `E:\FoundryVTT\ludusavi-backup.txt` (one line for each entry you want to back up):

  ```
  FoundryVTT Backups
  FoundryVTT Certs
  FoundryVTT Config
  FoundryVTT Data
  FoundryVTT Logs
  FoundryVTT Ludsavi
  FoundryVTT Modules
  ```
* `E:\FoundryVTT\ludusavi-backup.cmd`

  ```
  type .\ludusavi-backup.txt | .\ludusavi.exe backup --force
  pause
  ```

Then, when you want to do a backup, just double click on `ludusavi-backup.cmd`. You shouldn't need to configure any exclusions this way.

By the way, you have a typo of `Ludsavi` instead of `Ludusavi`, which means the `ludsavi.portable` file won't do anything 😅 (or maybe the file itself is named correctly and the typo is just in the custom game entry)

**Comment by mtkennerly** [comment]
The next release will allow you to disable the primary manifest entries by unchecking the manifest on the "other" screen. That way, it will only scan your custom entries.
