### ISSUE TITLE
Game not being detected

### ISSUE THREAD

**Issue by sjp761** [mtkennerly/ludusavi#356]
### Ludusavi version

v0.24.1

### Operating system

Linux

### Installation method

Standalone

### Description

For some reason Fallout New Vegas (GOG) installed on heroic does not get detected at all despite the game being installed.

### Logs

[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/15856004/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
Hi! From the log, it looks like it's being mapped to the original Fallout. Could you please give me the log for the following command as well?

```
RUST_LOG=ludusavi=trace ludusavi backup --preview "Fallout: New Vegas"
```

**Comment by sjp761** [comment]
[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/15856026/ludusavi_rCURRENT.log)

Here you go

**Comment by mtkennerly** [comment]
Thanks. For now, you can work around this by configuring an alias in Ludusavi on the custom games screen:

> ![image](https://github.com/mtkennerly/ludusavi/assets/4934192/0dc4bd12-d6f7-4950-a702-27e64644c0b0)

There are a few things going wrong here:

* First, Ludusavi tries to look up the game by its GOG ID, which is [1454587428](https://www.gogdb.org/product/1454587428). However, that's a secondary ID (DLC/editions/packages), and right now Ludusavi only matches the primary ID (which would be [1312824873](https://www.gogdb.org/product/1312824873)).
* Since that didn't match, Ludusavi tries to look up the exact title. Ludusavi expects `Fallout: New Vegas`, not `Fallout: New Vegas Ultimate Edition`, so again no match.
* Lastly, Ludusavi tries to normalize the title. Part of that means removing edition suffixes. Ludusavi guesses incorrectly that `New Vegas Ultimate Edition` is the edition name, rather than just `Ultimate Edition`, and so Ludusavi reduces it to just `Fallout`, which is a match for the wrong game.

I'll look into matching on secondary GOG IDs and maybe making the edition normalization less aggressive.

**Comment by sjp761** [comment]
Could it be a secondary ID thing be caused if I got it from Amazon prime?

**Comment by mtkennerly** [comment]
I'm not sure, to be honest. I see that GOG DB lists 1454587428 as a "game" and 1312824873 as a "package", but I'm not sure exactly what that implies for GOG. On [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Fallout:_New_Vegas), they're listed as:

```
|gogcom id    = 1312824873
|gogcom id side = 1454587428
```

But I do think Ludusavi should check both IDs anyway.

**Comment by mainrs** [comment]
I think the game ID is either the "parent ID" of all variations of a game on GOG, or it is the remnant of the old v1 API. Either way, API responses always return the availability of game IDs as "unavailable". I think it's also used to group packages together. 

A package is a unit of content. This can be the base game, language packs, DLCs, expansion passes, ...
In the case of The Witcher 3: Wild Hunt, the GOTY edition (Complete Edition) is a package for the same game ID and not a separate game. Whereas the Fallout game mentioned here seems to be its own game.

**Comment by mtkennerly** [comment]
Thanks, that's good info :)

For what Ludusavi is doing, I think we can get away without knowing if it's a game ID or package ID, though. Let's say you have some games in Playnite/etc where the names don't match Ludusavi, but the games have GOG IDs that we can use for lookup instead. Even if they're a mix of game/package IDs for some reason, all we really need to know is whether that ID appears in a PCGamingWiki article, so we can map from the ID to the article title.
