### ISSUE TITLE
Option to respect .gitignore files

### ISSUE THREAD

**Issue by BuyMyMojo** [mtkennerly/ludusavi#365]
### What's your idea?

An option for backups to ignore files and folders listed in .gitignore files would help cut down on setup time when bringing saves to a new system. place a .gitignore file in the saves folder and ignore specific files and restore that with ludusavi instead of needing to redo a script or exclusions in the future

**Comment by mtkennerly** [comment]
Hi! I don't think I would want to use `.gitignore` for this, but maybe we can find another solution for the same problem you're trying to solve. Could you give me some more details about what you were doing and the specific problems you faced?

**Comment by mtkennerly** [comment]
Closing for now since I don't plan to implement this specific approach, but I'd still like to know more about your use case. Perhaps it would be enough to copy over the [Ludusavi config file](https://github.com/mtkennerly/ludusavi/blob/master/docs/help/configuration-file.md) to the new system, since that tracks which saves were deselected?
