### ISSUE TITLE
Possible issue when save path uses user id

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#39]
Ludusavi detects files not configured in the PCGW/Manifest

Manifest:
![imagen](https://user-images.githubusercontent.com/1389286/90113392-e2a98180-dd16-11ea-8571-0f3ebef7e006.png)

PCGW:
![imagen](https://user-images.githubusercontent.com/1389286/90113411-ed641680-dd16-11ea-84bd-67cef4cb8c6c.png)

Ludusavi:
![imagen](https://user-images.githubusercontent.com/1389286/90113500-11275c80-dd17-11ea-8ebb-c18dfd0e6b62.png)

As seen in the screenshot, Ludusavi is trying to backup games in the root directory even when though they have not been stated in the manifest.

**Comment by mtkennerly** [comment]
There are a couple of factors here:

* PCGW ends the path with a slash to specifically mark it as a folder, whereas the manifest does not (since I didn't want to count on that convention being used consistently/correctly), so Ludusavi is looking for any files and folders that match.
* Each path is checked against each one of your roots. Steam roots match `storeUserId` with `[0-9]*` (digits-only), but Other roots match it with `*` (anything), and that's why those extra files are found.

A possible solution would be to allow configuring the user IDs to check for each root and/or being able to skip ID-dependent paths for a particular root, but I'm not sure if that's user-friendly enough. Definitely open to suggestions on this one.

**Comment by darklinkpower** [comment]
I don't think making it configurable and making it more complicated to the user would be a good idea. 

> since I didn't want to count on that convention being used consistently/correctly

Have you seen a case where `\` has been misplaced in an article? From all pages I've seen, there has never been one, only the opposite, where the `\` is missing when they are actually directories and not files.

To prevent issues like this, I would try to respect the `\` when found in PCGW articles and save them like that in the manifest to have more accurate information.

-  So for example: `%USERPROFILE%\AppData\LocalLow\path\to\<user-id>\` would be saved as a directory type in the manifest and only look for directories, not files.

- In the case of something like `%USERPROFILE%\AppData\LocalLow\path\to\<user-id>` (without the `\`) it would fallback and use the current behaviour and look for both files and directories.

This way the files lookup would be more accurate in cases where the article has been edited correctly with the `\` (which are almost all cases).

**Comment by mtkennerly** [comment]
That would prevent it from matching `Player-prev.log` and `Player.log` in this case, but it would still pick up on the `Unity` folder because of the second point that I mentioned. I think a solution that can avoid the false positive for `Unity` will also be sufficient to rule out any irrelevant files as well, so I don't think handling the trailing slash would ultimately be necessary.

> Have you seen a case where \ has been misplaced in an article? From all pages I've seen, there has never been one, only the opposite, where the \ is missing when they are actually directories and not files.

It's not especially common, but I've seen both ways at least once. Still, I would rather not rely on the difference since you can't have a file and folder with the same name anyway, so as long as the names can be sufficiently narrowed down. the type won't matter.

**Comment by mtkennerly** [comment]
I'm going to see if I can find out what some of the `<storeUserId>` paths look like for stores besides Steam. If it turns out that they're typically not relevant and that some other path gets used instead, then I may just skip checking `<storeUserId>` for Other roots by default (although I want to be careful there since backing up a few irrelevant files is still better than missing out on an important one).

**Comment by Lucki** [comment]
I think this also falls into this issue here:
I'm specifically looking at GTA IV in Proton which is set as `%USERPROFILE%\Documents\Rockstar Games\GTA IV\Profiles\<user-id>\ (Complete Edition)` in the wiki which gets resolved to `<winDocuments>/Rockstar Games/GTA IV/Profiles/<storeUserId>/ (Complete Edition)`.
Leaving the plain wrong ` (Complete Edition)` aside (that's an issue of the wiki entry) we're in a steam root (proton compatdata) so the `<storeUserId>` gets resolved to "`[0-9]*` (digits-only)" as you've mentioned earlier which is also wrong here because the `<storeUserId>` used represents the id from the rockstar game launcher an 8 char uppercase hex it seems.

![Bildschirmfoto von 2021-04-08 16-09-41](https://user-images.githubusercontent.com/1408843/114041845-2b551280-9885-11eb-8f5d-71b931032a3b.png)
![Bildschirmfoto von 2021-04-08 16-10-12](https://user-images.githubusercontent.com/1408843/114041839-2a23e580-9885-11eb-8f64-4004b877bf1b.png)

**Comment by mtkennerly** [comment]
Thanks, that's really good to know. So even if we got a comprehensive list of how each store normally handles its user IDs, that still wouldn't be a perfect solution. I can think of a couple of options left:

* Always use `*` for `<storeUserId>`.
  * Pro: we won't miss any saves by default.
  * Con: we'll grab irrelevant files, but at least people can create custom entries for any games where that takes up a bothersome amount of space.
* Add something to the manifest for game-specific `<storeUserId>` overrides.
  * Pro: this would work better in theory, if the data were filled out.
  * Con: it wouldn't be as easy for people to contribute as on PCGW, so the data probably wouldn't be very filled out.

I'm leaning toward the first option for now, in the next release. I'm open to the second option as an addition, but I'm just not sure how much use it would get. I suppose it can't hurt, though.
