### ISSUE TITLE
Date in save name and timezone

### ISSUE THREAD

**Issue by nicolasnobelis** [mtkennerly/ludusavi#392]
### What's your question?

Is it intentional that the hour part of the date in the save name doesn't reflect the timezone ?

![image](https://github.com/user-attachments/assets/3233ece3-dca6-417f-b5da-f9a1e79c153c)

This screenshot was made on a computer running at GMT+2: you can see the file was modified at 23:07 but the save contains 21:07.

EDIT: it seems to be a date in UTC due to the 'Z', but I wonder if it would be interesting to put the time offset information.

**Comment by mtkennerly** [comment]
Hi! Yes, the backup name always uses UTC. It *could* use your local time with an offset, but I'd rather avoid that since it could open up some odd behavior around daylight saving when your local time zone's offset changes. Ludusavi does convert the timestamps to your local time when displaying them in the GUI, though :)

**Comment by nicolasnobelis** [comment]
Thanks for your answer, you have a point !
