### ISSUE TITLE
Differential backups: deduplicating

### ISSUE THREAD

**Issue by Khorea1** [mtkennerly/ludusavi#397]
### What's your idea?

Firstly, thank you for this software - I'm using it daily and loving it. 

When using Ludusavi to backup large save files, I like to use the differential feature, as it makes compression and transferring go much faster. 

Unfortunately, I've noticed that when using it, most of the time it ends up duplicating the size of the backups, taking up a lot of storage space.

For example, with a structure of backups for a single game:

Full Backup 1: 
1. Save 1
2. Save 2

After playing for a while using Save 2 and creating another, 

Differential Backup 1:
1. Save 2 
2. Save 3

The older and now unused "Save 2" from the "Full Backup 1" will end up taking up space.

It would be great if some form of deduplication could be implemented in Ludusavi to avoid this.

**Comment by mtkennerly** [comment]
Hi! I'm glad you've found Ludusavi helpful :)

It sounds like, because the game has multiple save slots and you can make a new save whenever you want, you only care about the latest version of each slot. You would never want to restore an older copy of Save 2, but you do want to keep the latest copy of Save 1, Save 2, etc. Is that correct?

If that's right, I think the best solution here might be to have the option for game-specific retention settings. That way, you could have differential backups in general, but for this specific game, you would have a single full backup that gradually accumulates more save slots.

**Comment by Khorea1** [comment]
This is a surprisingly simple solution to my problem. I can't believe I didn't think of it before; I feel a bit embarrassed. Thanks for your support anyway.
