### ISSUE TITLE
Ludusavi linux archive having missing executable permissions

### ISSUE THREAD

**Issue by MRDGH2821** [mtkennerly/ludusavi#398]
### Ludusavi version

v0.25.0

### Operating system

Linux

### Installation method

Standalone

### Description

I'm using Chezmoi to manage my [dotfiles](https://github.com/MRDGH2821/dotfiles).
And I also using it to install some packages.
To auto download github releases, I'm using [dra](https://github.com/devmatteini/dra/)

I raised this issue first at DRA stating that ludusavi executable is not getting auto installed, but they say that ludusavi executable itself has insufficient executable permissions due to which DRA is not able to detect any executables.

https://github.com/devmatteini/dra/issues/232

Can this github release asset be re-uploaded with correct permissions?

**Comment by mtkennerly** [comment]
Hi! This seems to be a limitation of GitHub's `actions/upload-artifact`: https://github.com/actions/upload-artifact/issues/38

I suppose this makes a good argument for switching to `.tar.gz` instead of `.zip`, since it can preserve the permissions. I don't want to retroactively change that in the existing release, but I'll look into doing it for the next one.

**Comment by MRDGH2821** [comment]
This is indeed a good idea. I'll let this issue be open until the next release.

**Comment by mtkennerly** [comment]
This is now available with v0.26.0 \:D https://github.com/mtkennerly/ludusavi/releases/tag/v0.26.0
