### ISSUE TITLE
 Ludusavi does not recognize D drive or E drive

### ISSUE THREAD

**Issue by johnnyhunt2000** [mtkennerly/ludusavi#405]
### Ludusavi version

v0.25.0

### Operating system

Windows

### Installation method

Standalone

### Description

Every time I try backing up a save to either my D: Drive or my E: Drive, I get a "No save data found" message on Playnite. Backing up the saves to my C: Drive works, but I don't have room on there so this is a very frustrating bug. All my root folders are correct, the path direction is correct, but I am still getting errors. Please fix this ASAP
![Screenshot 2024-10-13 221636](https://github.com/user-attachments/assets/869e375c-1f69-4afd-be8f-fce5853f251d)
![Screenshot 2024-10-13 221315](https://github.com/user-attachments/assets/6970036d-a835-4f69-bbdb-b3d26f2cb91b)
![Screenshot 2024-10-13 221259](https://github.com/user-attachments/assets/698f26a5-ab1e-4698-a1c8-9f32d62a3f48)
![Screenshot 2024-10-13 221229](https://github.com/user-attachments/assets/9eb0814a-dcf0-4df6-b5e5-27e31c8bdffd)

**Comment by mtkennerly** [comment]
Hi! Try changing your first Steam root to just `D:\SteamLibrary` :)

**Comment by johnnyhunt2000** [comment]
"No save data found"
![new2](https://github.com/user-attachments/assets/d91942ef-c098-4bf4-8bf3-cf384ba024b1)
![new1](https://github.com/user-attachments/assets/9d0bafc2-a491-46e8-92dc-aa3b78023de1)

**Comment by johnnyhunt2000** [comment]
Ok so I fixed it my renaming my E: Drive to D: Drive resetting my PC, and it found the folders. Not sure what the issue was in the first place, but it seems to work fine now. Sorry for the confusion

**Comment by mtkennerly** [comment]
I just noticed your custom game entry for `DOOM 3`. There are a few issues I can see:

* Ludusavi knows the game by its PCGamingWiki article title, which is capitalized as `Doom 3`, so the title doesn't match your custom entry. If you were just scanning in Ludusavi itself, then it'd essentially ignore your custom `DOOM 3` entry and just find the default `Doom 3` data instead.
* Since you're using the Playnite plugin, it tries a few techniques to map from the title in Playnite to the standard title. If the game in Playnite has a Steam ID set in the metadata, then it should be able to find the game by that ID. Could you show me a screenshot of the game properties in Playnite?
* In your custom entry, you have `<path-to-game>`, which is how it's displayed on PCGamingWiki, but that's not the syntax that Ludusavi understands. The equivalent in Ludusavi would be `<base>`. You can reference the placeholder table here: https://github.com/mtkennerly/ludusavi-manifest

**Comment by johnnyhunt2000** [comment]
Renaming it to just Doom 3 actually breaks it, it doesn't recognize, 
![new3](https://github.com/user-attachments/assets/df62f1e1-d882-4ff4-8292-8e6626d86930)
![new5](https://github.com/user-attachments/assets/4c97e138-4348-4ec8-b412-957ee5572d0b)
![new4](https://github.com/user-attachments/assets/4a83cf5b-b268-467c-9fb8-9e4fd97e4b91)
Also I am aware that "path-to-game" is not the correct file path, but for some reason it works so that's why its like that

**Comment by mtkennerly** [comment]
To be clear, you should just delete the custom entry here.

If you rename the custom entry to `Doom 3`, then it will override the default entry, and since your custom path is invalid, it naturally won't find anything.

**Comment by johnnyhunt2000** [comment]
Deleting the custom entry worked as well, the reason why I even made a custom entry was because I was trying to fix the problem lol. Thank you for the help though I appreciate it
