### ISSUE TITLE
Show game list in backup/restore confirmation message

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#42]
In order to prevent mistakes and give more info to the user. When selecting a large number of games it would be better if the list was scrollable.

![imagen](https://user-images.githubusercontent.com/1389286/90301036-08dc3800-de63-11ea-89d5-e7f5ed2b9b01.png)

![imagen](https://user-images.githubusercontent.com/1389286/90301040-10034600-de63-11ea-83e1-8bc2cf9b089c.png)

**Comment by mtkennerly** [comment]
Personally, I think that would be overkill since you can just hit cancel to go back to the full list.

How about if the message included some extra info for these scenarios?

* If there hasn't been a full scan yet (or if it's been invalidated by config changes), then suggest doing a preview first to prevent surprises.
* If a full scan has been done (and is still valid), then show the number of games that will be included in the operation.

**Comment by mtkennerly** [comment]
I've adjusted the messaging to suggest doing a preview first, for a little extra safety.

Eventually, the grey top and bottom of the confirmation screens will be transparent, which would let you see the total games and disk space behind it. Because of that, I'd rather not add it into the confirmation message itself.

## Backup
![image](https://user-images.githubusercontent.com/4934192/90355838-8ba7f300-e01b-11ea-808d-f87e32dfdfec.png)

## Restore
![image](https://user-images.githubusercontent.com/4934192/90355832-89459900-e01b-11ea-9f7c-cc24501b5ef2.png)
