### ISSUE TITLE
Make it easier to delete save files (quick open save locations)

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#46]
I'm not sure if this would be useful to everyone so it's just an idea. I've wanted to play games that I left halfway and I just preferred to delete the saves and start over, but to do that you have to go to PCGW and search for the save location(s). Having an option to do it within Ludusavi would be useful for this and similar cases. If implemented, I think having a button next to the game name would work and also having to accept an extra confirmation dialogue after pressing the button to prevent mistakes.

![imagen](https://user-images.githubusercontent.com/1389286/90327263-5b971c00-df57-11ea-91b8-569ab5393046.png)

With this, Ludusavi could completely manage the game saves and be a global save manager for all operations.

**Comment by mtkennerly** [comment]
I have somewhat mixed feelings about this. On one hand, I do think Ludusavi should help to ease the use case you mentioned, but on the other hand, there are some complications:

* The delete button would need to be per file, not per game, since you probably wouldn't want to delete stuff like config files and screenshots.
* A lot of games let you delete your saves from within the game itself, which I think would be the better option when it's available. For example, if a game stores multiple saves in the same file, Ludusavi could only delete all of them at once, whereas the game could let you choose just one.
* You may have to disable things like Steam Cloud sync along with deleting the files, so it wouldn't "just work" - someone might use the feature and wonder why their saves came right back.
* In general, I don't like giving users potential footguns. What if you have a game where deleting your saves causes the "recent quick saves" viewer to crash (like if the recent file list is stored separately, and it's not expecting those files to go missing)? I feel like having a built-in delete option is also a promise that it's safe to use - of course, I could add a warning that it isn't, but it still makes me a bit uneasy.

I think a decent compromise would be to have a way to quickly pull up the files in your file browser. That way, you could do a variety of different things, like delete them, edit them, or move them around. What do you think?

**Comment by darklinkpower** [comment]
So opening the directories where the pointed files are stored? Yeah, I think that could also work. BTW, before opening another issue, what would you think about having a button that opens the respective PCGW article of a game next to this one? It could make it easier to view information and edit them if neccesary.

**Comment by mtkennerly** [comment]
Hmm, I hadn't considered that, but it's not a bad idea. My only concern might be how often people use it vs how much space it takes on each game's row, but I could just make the icon a bit narrower to compensate. So yeah, I think that would be a nice addition, considering how important PCGW is to this project.

(I also need to see if there's a good, cross-platform way to open a link in the default browser. It looks like [this crate](https://crates.io/crates/opener) will work, but I'll need to test it out.)

**Comment by darklinkpower** [comment]
If space is a concern, a right click menu coud be another option as long as it's possible to add. It could also be more future proof since more things could be added in the future if needed without having to worry about space.

**Comment by mtkennerly** [comment]
Yeah, that would be a good option long-term, but unfortunately it isn't feasible with the GUI library ([Iced](https://github.com/hecrj/iced)) just yet. I think it'll be fine for now, though.

**Comment by mtkennerly** [comment]
Went ahead and added the PCGW button first:

![open-wiki-2](https://user-images.githubusercontent.com/4934192/90417626-fab83280-e081-11ea-8792-5d7c5a07d462.gif)

**Comment by mtkennerly** [comment]
This is now implemented:

![open-folder-2](https://user-images.githubusercontent.com/4934192/91650069-e3e1ea80-ea48-11ea-952f-6db528b102ea.gif)

If all goes as planned, I'd like to get a new release out with this sometime tomorrow.
