### ISSUE TITLE
Self backup

### ISSUE THREAD

**Issue by Skyline404** [mtkennerly/ludusavi#54]
Dont know why, bit Ludusavi wants to backup ist own config

![WindowsTerminal-18-15-22-J1oxg](https://user-images.githubusercontent.com/32412867/96367339-ebbf3080-1155-11eb-96ed-3f74b4f2e953.jpg)

**Comment by mtkennerly** [comment]
Thanks for reporting this! The save paths for the Scrap Garden games are formatted unusually on PCGamingWiki. Because of that, my importer script is misinterpreting that data and thinks that the paths mean something else. I'll do two things to fix this:

* Normalize the formatting on PCGamingWiki
* Put in a safeguard in the importer script in case any similar formatting is introduced in another article

**Comment by mtkennerly** [comment]
Both of those steps are now complete. The next time you open Ludusavi, it will automatically download the corrected data to fix this.
