### ISSUE TITLE
Add option to add additional home root directories.

### ISSUE THREAD

**Issue by micke1m** [mtkennerly/ludusavi#61]
I have modified my Steam .desktop file to use a custom home directory to keep steam files and saves separated from the regular home directory. Would be nice if ludusavi could detect saves in additional home directories other than the  default one. For example it could be as an additional radio button besides Steam and Other.

**Comment by mtkennerly** [comment]
Hi! Although Ludusavi currently only auto-detects the standard locations, you can add as many custom ones as you need. You can add a new root for the custom home folder (or modify the auto-detected one if you don't need it), keep the radiobutton as Steam (because the contents of the folder would be organized per normal Steam rules, even if the folder location is custom), and it should pick up your saves when you scan again.

As far as the auto-detection goes, #58 would add some related improvements, but I'm not sure about the implications of detecting `.desktop` files. It would probably depend on the `.desktop` file having a standard name and location in order to avoid false positives.

**Comment by micke1m** [comment]
Ludusavi does not detect additional home directories even if I add it as another Steam root.
I have `HOME=/ssd/steamhome` in my Steam.desktop file, and add `/ssd/steamhome` as well as the normal Steam directory: `/ssd/steamhome/.local/share/Steam`. If I move a save from my real home folder to the `/ssd/steamhome`, the number of games ludusavi detects goes down.

Also I do not imply auto-detection in .desktop files should be added, because it's probably a very uncommon use case. I only want to manually add an additional home directory.

**Comment by mtkennerly** [comment]
Oh, I get what you mean now. I was only considering the impact on where `.local/share/Steam` ends up, but not that the individual games would also respect the custom home and add their own files there. I'll look into adding support for this.

**Comment by micke1m** [comment]
Awesome! And yes the games do respect the custom folder when they are launched through Steam.
