### ISSUE TITLE
Linux Mint doesn't recognise "ludusavi" as an executable, even if I allow it to execute like a program

### ISSUE THREAD

**Issue by OmegaOmega** [mtkennerly/ludusavi#71]
I'm using Linux Mint 20.1 Cinnamon, kernel 5.4.0-72-generic

So, I was trying to use the executable available. I am not that savvy with Linux directory structure, so I just all my portable apps into "/home/[USER]/portable". When I try to open the executable with something else, even if I check the "allow executing file as program" mark in its permissions. 

I managed to install ludusavi installing Rust and using Cargo, but the far easier way didn't work. Go figure.

**Comment by mtkennerly** [comment]
Thanks for the report. Some questions for you:

* Is there a specific error message when you double click on the executable, or does nothing happen at all?
* What happens if you open a terminal and run `~/portable/ludusavi`?

I'm not sure about Mint specifically, but you may just need to create a `.desktop` file and double click on it instead. For example, you might try making a `ludusavi.desktop` like this (also make this file executable as well and substitute `[USER]`):

```
[Desktop Entry]
Name=Ludusavi
Type=Application
Exec=/home/[USER]/portable/ludusavi
Terminal=true
```
