### ISSUE TITLE
Add option to keep multiple copies of backups

### ISSUE THREAD

**Issue by 1024mb** [mtkennerly/ludusavi#74]
Coming from GSM and it's laginess I find this tool really good. Now, one thing that would make it even better is if it could keep multiple copies of the backups and backup only if files have changed, just like in GSM a checksum is made then if checksum has changed or there are new files it performs the backup otherwise it skips it.

**Comment by mtkennerly** [comment]
Hi! I'm glad you've found it helpful \:D Regarding the different parts of this:

* Skip if not changed: This is already implemented. Ludusavi won't re-copy any files that are the same as in the existing backup. I would definitely keep that behavior for compressed backups as well.
* Compression: Tracked by #47.
* Multiple copies: Agreed, this would be good to add. I briefly mentioned it in #47, but it's good to track it explicitly since it could be implemented independently.

**Comment by DragonightFury** [comment]
So I've been testing Ludusavi, and apparently it does copy files that already exist in the backup, cause disk write speeds are high when I'm backing up the same fiiles. Shouldn't it be just read speeds?

**Comment by mtkennerly** [comment]
@DragonightFury How is your `merge` option configured? When it's disabled, the backup directory is deleted first.

If it's enabled, then I'm not sure why you'd see that. This is the check for identical files:

https://github.com/mtkennerly/ludusavi/blob/edb55fdb1d22693e5f76bc8da8646351ad0ac848/src/prelude.rs#L694-L703

It will only proceed to the copy/write code if the files have different content (`Ok(false)`). I tried adding some logging to confirm, and I do see it consistently following the `Ok(true)` branch when I repeatedly back up the same game.

**Comment by DragonightFury** [comment]
@mtkennerly I'm using ludusavi-playnite plugin. On their page it says that it has this option enabled. I'm still not sure because if I delete some file from the saves directory, after i backup, it gets deleted too

**Comment by mtkennerly** [comment]
Gotcha, yeah, the Playnite plugin always uses merging. The full behavior is:

* Keep the existing backup folder
* If any files are missing or have different content in the backup folder, then copy them over
* If any outdated/irrelevant files exist in the backup folder (e.g., a backed up save that no longer exists in the game's live save location), then remove them

Is the third point what you're referring to?

**Comment by redactedscribe** [comment]
First of all, thank you for creating Ludusavi and using 🦀 to make it a reality. Seeing Rust in use always make me happy. However there are some features I consider missing from Ludusavi, multiple backups being one of them. Here I outline my thoughts on how this feature should be implemented and what I think would be a cohesive user experience.

I'll start by suggesting that when pressing the _Back up_ button, the user should be presented the backup method options: _Merge_ and _Recreate_. This elevates the _Merge_ option to be on par with _Recreate_ as a standalone backup method.

If backup methods and their options were presented at the top of the pop-up shown after _Back up_ is pressed, then the descriptive text could be placed below and dynamically change to display what actions will occur based on the currently selected choices. Once the user is happy with their choices and the described result, they can press _Continue_ to begin the process.

This kind of UX flow would keep all the backup decision-making on a single page and allow for it to be expanded once a multiple backups feature is introduced. I think the backup methods should be presented to the user categorised by type and method (this assumes future features):

Backup type | Backup method 1 | Backup method 2
-|-|-
One backup per game | Merge (merge with backup location) | Recreate (delete and recreate backup location)
Multiple backups per game | Full backups only | Full backups with differentials

Assuming its implementation, _Full backups only_ would be a full backup like _Recreate_ but instead of deleting and recreating the configured _Back up to_ directory, simply increment the subdirectories contained within it by appending some new value to them, a good candidate being be the date and time, up to the current second, at the moment that the process starts (e.g. "Game Name [20220721-131259]"). I think I read somewhere that you'd be moving to making all backups be compressed archives, which I agree with, but I also think an _Other_ settings option to keep using plain folders (i.e. skip archiving altogether) would be appreciated for those unconcerned with the storage used or those who want immediate access to the backed up files.

I propose that the settings which determine how _Full backups only_ and _Full backups with differentials_ work should be controlled at a global level via the _Other_ tab. There we could set some values:

_Other > Full backups only_:

- A limit on the number of full backups to create before Ludusavi starts to prune them. Could be set to 0 for an unchecked number of full backups.

_Other > Full backups with differentials_:

- A limit on the number of diff backups to create post the full backup before a new chain is created (a chain being a full backup plus its diffs).
  - An option to only ever store one diff in a chain to keep storage usage down (a diff would be created and the old one deleted each backup until the parent option's limit was reached and a new chain begins).
- The number of full _backup chains_ to keep. When the limit of diffs is reached, and if some num_prev_chains_to_keep were set to "2", then the previous two full backups and their related diffs will always be kept. If a third chain existed and was the eldest, delete that when starting a new chain.

With multiple backup methods to choose from, an option in the _Other_ tab(?) of Ludusavi could define the preferred method so that it would be preselected for us each time we press _Back up_ (but still be overridable). _Recreate_ (with _Merge_ enabled) should likely be the default because it's the simplest, and it would prevent accidental loss which is possible with _Merge_ disabled.

Problems I've not thought about:

- What happens when you perform a _Full backups only_ on a directory that was used as a _Recreate_ backup previously? Maybe the _One backup per game_ and _Multiple backups per game_ backup types should have separate _Back up to_ paths?

I'm sure these ideas will need some work or restructuring when it comes to actual implementation. I was attempting to adhere to how things currently operate, but perhaps a more refined approach will become more obvious once you attempt to code. Hopefully some of what I've written is food for thought.

Thanks.

---

In case you aren't familiar with incremental and differential backups: A Differential backup is a backup containing the difference between itself and its related full backup. This means any diff backups created before the latest one can be deleted without consequence as long as the full backup remains present (assuming that restoring the most up-to-date files is your goal); 1 full + latest diff = latest backed up files. A full plus a diff can be considered a chain, although I think this term is more suitable for incremental backups which require all previous incs and the full backup to exist to be able to restore the most up-to-date backed up files. A loss of an inc means that the chain is now broken resulting in a partial loss of data post the breaking point of the chain. Using diff backups is more resilient but consumes more storage, whereas the inverse is true for incs. Diffs are the way to go for simplicity's sake in the context of a games user data backup utility.

**Comment by mtkennerly** [comment]
This is now implemented! Preview:

> https://user-images.githubusercontent.com/4934192/184405927-5474cea5-aa01-40dc-b06b-0770a72207d9.mp4

**Comment by redactedscribe** [comment]
Thanks @mtkennerly!
