### ISSUE TITLE
Ignore directories

### ISSUE THREAD

**Issue by FayneAldan** [mtkennerly/ludusavi#78]
There should be a config option to completely ignore files saved in specified directories. This could be useful if the user's Documents folder (a common save location) is already being backed up (perhaps to a cloud service such as OneDrive or Dropbox) or for games that save to the install directory and the game is installed to a backup drive (i.e. `E:\Games`).

**Comment by mtkennerly** [comment]
I think this is a good idea :+1: I haven't been interested in adding a per-game ignore option, but you make a good case for a global option.

**Comment by Sanaki** [comment]
Per-game ignore seemed pretty unnecessary to me until I saw that RetroArch is showing as a 6.19TiB backup because symlinks are apparently followed fully as well. Needless to say that's not a backup I want to do. Seems like a directory ignore should let me ignore the symlink in question, so that's a use case for me as well.

**Comment by FayneAldan** [comment]
This suggestion isn't for per-game ignore. If you want something like that, you can just edit the game entry in the GUI. This suggestion is to ignore a directory for all games in case a common directory (like Documents) is being backed up already to, for example, a cloud service. 


Unrelated, but for RetroArch you can also change the Directory settings to change your save and state directories to OneDrive or something. Use the desktop menu and you can change the directories with an actual textbox and folder selector.

**Comment by Sanaki** [comment]
I'm aware. My point was that ignoring a subdirectory would serve my purpose here. And I'm quite familiar with directory remapping in RetroArch, but that also removes cloud saves.

**Comment by FayneAldan** [comment]
> And I'm quite familiar with directory remapping in RetroArch, but that also removes cloud saves.

I mean, only the Steam version has built-in cloud saves and the Steam version has limitations. However, if you already have Steam backing up your RetroArch saves, you can probably disable backing up RetroArch in Ludusavi.

**Comment by mtkennerly** [comment]
Just a note from https://github.com/mtkennerly/ludusavi/issues/68: In the list of files found, there could be checkboxes to quickly add or remove them from the ignore list. If two games shared a path, it would be toggled for both at the same time, since it would be a global list of ignored paths.

**Comment by mtkennerly** [comment]
I ended up implementing two things for this:

* Globally ignored paths/registry, which won't even show up in the list of scanned files
* Game-specific ignored paths/registry, which will show up but can be toggled on and off with checkboxes in the list of scanned files

I had previously not wanted to add the latter because I felt that custom game entries could solve the same problem. However, I encountered a use case where a custom game is not sufficient:

* One of the save folders for Trails in the Sky is `<Steam-folder>\userdata\<user-id>\251150\remote\FC\`
* One of the save folders for Trails in the Sky SC is `<Steam-folder>\userdata\<user-id>\251150\remote\SC`

Trails in the Sky SC has a different Steam app ID, but stores its saves in the first game's app ID folder for some reason. When Ludusavi scans a game with a known Steam ID, it automatically scans the whole app ID folder, which means that the SC saves are picked up when scanning the first game. Because the app ID check is an automatic addition, there's no way to disable it from a custom game, and because you still want the FC folder when backing up the first game, you can't just ignore it globally.
