### ISSUE TITLE
Ludusavi attempts to backup the entire game folder for Little Witch Academia: Chamber of Time [Windows, Steam]

### ISSUE THREAD

**Issue by ltctceplrm** [mtkennerly/ludusavi#80]
On the [PC Gaming Wiki](https://www.pcgamingwiki.com/wiki/Little_Witch_Academia:_Chamber_of_Time) it shows the configuration file as `<path-to-game>\LWA.cfg` but ludusavi it attempts to back up the entire game folder instead (10GB).
It says the paths are `<base>/*` and `<winLocalAppData>/BANDAI NAMCO Entertainment/Little Witch Academia/14608/Save`

I'm using the latest ludusavi version (v0.10.0) on windows

**Comment by mtkennerly** [comment]
Hi! This is because the PCGW article incorrectly used the `<code></code>` tag in the save path. I've [corrected the article](https://www.pcgamingwiki.com/w/index.php?title=Little_Witch_Academia:_Chamber_of_Time&diff=1179311&oldid=1170999), so the next nightly manifest update will resolve this issue.

**Comment by ltctceplrm** [comment]
Thank you
