### ISSUE TITLE
Alphabetical sort, DLCs and sequels

### ISSUE THREAD

**Issue by davidhesselbom** [mtkennerly/ludusavi#82]
The sorting algorithm used has trouble with the ordering of certain things, it seems. I don't know whether a better algorithm exists...

![alphasort](https://user-images.githubusercontent.com/4319680/145786999-ef67f6cf-99b2-4b50-9a25-25f8e454c006.PNG)

**Comment by davidhesselbom** [comment]
As an aside, Company of Heroes 2 and its 2 DLCs are not listed separately in Steam...

**Comment by mtkennerly** [comment]
The sorting in that screenshot is normal, since spaces sort before colons. Unfortunately, it's not so intuitive for humans, but there's not a great way to handle it automatically. The reason stuff in programs like Steam can sort differently is because the developer can register a special name that's used just for sorting.

The DLC is listed separately because each one has a different article on PCGamingWiki. I don't know think there's a good way to consolidate those on Ludusavi's side, but hopefully such cases are fairly rare.
