### ISSUE TITLE
Duplicates shown of games not installed

### ISSUE THREAD

**Issue by minimeee** [mtkennerly/ludusavi#97]
Hi!

 After a recent update (few weeks ago), ludusavi shows my saves of "Kingdom Come: Deliverance" as a duplicate of both "Command & Conquer 3" and "Command & Conquer: Red Alert 3" (see attached screenshot), although they were never installed on my system.
![screenshot](https://user-images.githubusercontent.com/5322305/165837885-71667775-d1bd-4e89-b4f4-f3348a32731b.png)

**Comment by mtkennerly** [comment]
Thanks for pointing this out! The paths in the manifest for Command & Conquer: Tiberium Wars were messed up (because of a previous version of the manifest updater script) and just needed to be re-parsed. I've updated the manifest (https://github.com/mtkennerly/ludusavi-manifest/commit/9518fa6fce31f0495378f051bceda9981ba44688), so this should be resolved the next time you launch Ludusavi.
